name 'chef-contrast-teamserver'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'All Rights Reserved'
description 'Installs/Configures Contrast Security TeamServer'
long_description 'Installs/Configures Contrast Security TeamServer on Linux or Windows'
version '0.1.4'
chef_version '>= 12.14' if respond_to?(:chef_version)
depends 'chrome', '~> 4.0.2'
depends 'vcruntime', '~> 1.2.0'
depends 'phantomjs2'
